// <auto-generated />
using ApiDesafio.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDesafio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ApiDesafio.Domain.Entities.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeUnico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ambiente");
                });

            modelBuilder.Entity("ApiDesafio.Domain.Entities.ConfiguracaoAmbienteFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtivoNesteAmbiente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureToggleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("FeatureToggleId");

                    b.ToTable("ConfiguracaoAmbienteFeature");
                });

            modelBuilder.Entity("ApiDesafio.Domain.Entities.FeatureToggle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtivoGlobalmente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomeUnico")
                        .IsUnique();

                    b.ToTable("FeatureToggle");
                });

            modelBuilder.Entity("ApiDesafio.Domain.Entities.ConfiguracaoAmbienteFeature", b =>
                {
                    b.HasOne("ApiDesafio.Domain.Entities.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiDesafio.Domain.Entities.FeatureToggle", "FeatureToggle")
                        .WithMany()
                        .HasForeignKey("FeatureToggleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("FeatureToggle");
                });
#pragma warning restore 612, 618
        }
    }
}
